import type { Creator } from "@/components/dashboard/creators/CreatorsClient";

/**
 * Test-only creator data for the Brand Portal's Creators tab, kept
 * completely separate from the real Supabase `creators` table (see
 * src/app/brand/creators/page.tsx, which concatenates this array onto
 * the real query result). Every id is prefixed "mock-" so it can never
 * collide with a real UUID and is trivial to find and delete — removing
 * this file and the one import of it fully reverts the Creators tab to
 * real-data-only, no UI changes required.
 *
 * Shaped identically to the real `Creator` type (including nullable
 * performance fields, since real creators genuinely have those as null
 * today) so the UI can't tell these apart from real rows.
 */
export const MOCK_CREATORS: Creator[] = [
  {
    id: "mock-0000-0000-0000-0000-000000000001",
    name: "Amara Chen",
    headline: "AI-powered marketing for B2B SaaS teams",
    vertical: "marketing-ops",
    industry_tags: ["AI", "Marketing"],
    country: "United Kingdom",
    follower_count: 61100,
    price_per_post: 188,
    median_views: 17300,
    cpm: 11,
    engagement_rate: 5.4,
    last_posted_at: "2026-09-04",
    linkedin_url: "https://linkedin.com/in/amara-chen-mock",
    avatar_url: null,
    bundle_price: 625,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000002",
    name: "Rohan Verma",
    headline: "Building the AI layer for modern SaaS pricing",
    vertical: "vertical-saas",
    industry_tags: ["AI", "SaaS"],
    country: "United States",
    follower_count: 10600,
    price_per_post: 94,
    median_views: 8300,
    cpm: 11,
    engagement_rate: 4.8,
    last_posted_at: "2026-09-08",
    linkedin_url: "https://linkedin.com/in/rohan-verma-mock",
    avatar_url: null,
    bundle_price: 310,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000003",
    name: "Ines Duarte",
    headline: "RevOps systems that survive a Series B",
    vertical: "revops",
    industry_tags: ["RevOps", "CRM", "B2B"],
    country: "Portugal",
    follower_count: 24700,
    price_per_post: 150,
    median_views: 9100,
    cpm: 13,
    engagement_rate: 6.1,
    last_posted_at: "2026-08-29",
    linkedin_url: "https://linkedin.com/in/ines-duarte-mock",
    avatar_url: null,
    bundle_price: 495,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000004",
    name: "Tomas Berg",
    headline: "Open-source devtools, adoption, and PLG loops",
    vertical: "devtools",
    industry_tags: ["DevTools", "Software"],
    country: "Sweden",
    follower_count: 132000,
    price_per_post: 640,
    median_views: 41000,
    cpm: 9,
    engagement_rate: 3.2,
    last_posted_at: "2026-09-10",
    linkedin_url: "https://linkedin.com/in/tomas-berg-mock",
    avatar_url: null,
    bundle_price: 2100,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000005",
    name: "Sade Okonkwo",
    headline: "People ops for distributed teams — HR-tech reviews",
    vertical: "hr-tech",
    industry_tags: ["HR", "SaaS"],
    country: "Nigeria",
    follower_count: 8200,
    price_per_post: 65,
    median_views: null,
    cpm: null,
    engagement_rate: null,
    last_posted_at: null,
    linkedin_url: "https://linkedin.com/in/sade-okonkwo-mock",
    avatar_url: null,
    // Deliberately null — exercises the "no bundle price set" honest path
    // in the View Profile modal (only "Single post" is offered).
    bundle_price: null,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000006",
    name: "Diego Fuentes",
    headline: "Fintech compliance, explained for founders",
    vertical: "fintech",
    industry_tags: ["Fintech", "Finance"],
    country: "Spain",
    follower_count: 47600,
    price_per_post: 320,
    median_views: 15400,
    cpm: 14,
    engagement_rate: 4.1,
    last_posted_at: "2026-09-01",
    linkedin_url: "https://linkedin.com/in/diego-fuentes-mock",
    avatar_url: null,
    bundle_price: 1050,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000007",
    name: "Priya Ramaswamy",
    headline: "Product-led growth: onboarding, activation, retention",
    vertical: "product",
    industry_tags: ["Product", "Growth / GTM", "SaaS"],
    country: "India",
    follower_count: 68000,
    price_per_post: 410,
    median_views: 22800,
    cpm: 10,
    engagement_rate: 5.9,
    last_posted_at: "2026-09-06",
    linkedin_url: "https://linkedin.com/in/priya-ramaswamy-mock",
    avatar_url: null,
    bundle_price: 1350,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000008",
    name: "Marcus Webb",
    headline: "Cold outbound is dead — creator-led pipeline isn't",
    vertical: "sales-tech",
    industry_tags: ["Sales", "Outreach", "B2B"],
    country: "United States",
    follower_count: 187000,
    price_per_post: 900,
    median_views: 58000,
    cpm: 8,
    engagement_rate: 2.9,
    last_posted_at: "2026-09-09",
    linkedin_url: "https://linkedin.com/in/marcus-webb-mock",
    avatar_url: null,
    bundle_price: 2950,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000009",
    name: "Yuki Tanaka",
    headline: "E-commerce ops and the tools stack behind 8-figure DTC",
    vertical: "marketing-ops",
    industry_tags: ["E-commerce", "Marketing"],
    country: "Japan",
    follower_count: 5200,
    price_per_post: 45,
    median_views: 2100,
    cpm: 16,
    engagement_rate: 7.8,
    last_posted_at: "2026-08-20",
    // No LinkedIn on file yet — exercises the "handle missing URL
    // gracefully" path deliberately, not an oversight.
    linkedin_url: null,
    avatar_url: null,
    bundle_price: null,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000010",
    name: "Lena Kowalski",
    headline: "Cybersecurity GTM for teams selling to enterprise",
    vertical: "devtools",
    industry_tags: ["Cybersecurity", "B2B"],
    country: "Germany",
    follower_count: 29400,
    price_per_post: 275,
    median_views: 9800,
    cpm: 12,
    engagement_rate: 4.5,
    last_posted_at: "2026-09-02",
    linkedin_url: "https://linkedin.com/in/lena-kowalski-mock",
    avatar_url: null,
    bundle_price: 900,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000011",
    name: "Caleb Osei",
    headline: "Design systems and the business case for good UX",
    vertical: "product",
    industry_tags: ["Design", "Product"],
    country: "Ghana",
    follower_count: 15900,
    price_per_post: 120,
    median_views: 4600,
    cpm: 13,
    engagement_rate: 6.6,
    last_posted_at: "2026-07-28",
    linkedin_url: "https://linkedin.com/in/caleb-osei-mock",
    avatar_url: null,
    bundle_price: 400,
  },
  {
    id: "mock-0000-0000-0000-0000-000000000012",
    name: "Freya Solheim",
    headline: "Vertical SaaS founder advising other vertical SaaS founders",
    vertical: "vertical-saas",
    industry_tags: ["SaaS", "B2B", "Growth / GTM"],
    country: "Norway",
    follower_count: 12900,
    price_per_post: 175,
    median_views: null,
    cpm: null,
    engagement_rate: null,
    last_posted_at: null,
    linkedin_url: "https://linkedin.com/in/freya-solheim-mock",
    avatar_url: null,
    bundle_price: 575,
  },
];
