import Link from "next/link";

export default function Home() {
  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-6 bg-zinc-50 px-4 text-center dark:bg-black">
      <p className="text-sm font-medium uppercase tracking-wide text-zinc-500">
        Where B2B brands work with creators
      </p>
      <h1 className="max-w-xl text-4xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-50">
        The B2B LinkedIn Creator Marketplace
      </h1>
      <p className="max-w-md text-lg text-zinc-600 dark:text-zinc-400">
        Find the creators your buyers already trust, launch campaigns in
        days, and track the clicks, leads and pipeline generated by every
        post.
      </p>
      <div className="mt-2 flex flex-col gap-3 sm:flex-row">
        <Link
          href="/signup"
          className="rounded-full bg-zinc-900 px-6 py-3 text-sm font-medium text-white hover:bg-zinc-700 dark:bg-zinc-50 dark:text-zinc-900 dark:hover:bg-zinc-200"
        >
          Start for free
        </Link>
        <Link
          href="/login"
          className="rounded-full border border-zinc-300 px-6 py-3 text-sm font-medium text-zinc-700 hover:bg-zinc-100 dark:border-zinc-700 dark:text-zinc-200 dark:hover:bg-zinc-900"
        >
          Log in
        </Link>
      </div>
    </div>
  );
}
